

insert into entries (name,age,club,category) values 
  ("Adam", 18, "Arniston Artizsts", 1),
  ("Bill", 22, "Bobs Brawlers", 1), 
  ("Charles", 22, "Bobs Brawlers", 1), 
  ("David", 22, "Bobs Brawlers", 1), 
  ("Edward", 22, "Bobs Brawlers", 1), 
  ("Frank", 22, "Bobs Brawlers", 1), 
  ("Grahame", 22, "Bobs Brawlers", 1), 
  ("Harry Hill", 22, "Bobs Brawlers", 1), 
  ("Isengard", 22, "Bobs Brawlers", 1), 
  ("Jerry Lee", 22, "Bobs Brawlers", 1), 
  ("Karl", 22, "Bobs Brawlers", 2), 
  ("Lisa", 22, "Bobs Brawlers", 2), 
  ("Mary", 22, "Bobs Brawlers", 2), 
  ("Naomi", 22, "Bobs Brawlers", 2), 
  ("Ophelia", 22, "Bobs Brawlers", 2), 
  ("Persephone", 22, "Bobs Brawlers", 2), 
  ("Queenie", 22, "Bobs Brawlers", 2), 
  ("Rosamund", 22, "Bobs Brawlers", 2), 
  ("Stephanie", 22, "Bobs Brawlers", 2), 
  ("Tamsin", 22, "Bobs Brawlers", 2), 
  ("Alfie", 22, "Bobs Brawlers", 3), 
  ("Bob", 22, "Bobs Brawlers", 3), 
  ("Cameron", 22, "Bobs Brawlers", 3), 
  ("David", 22, "Bobs Brawlers", 3), 
  ("Ellie", 22, "Bobs Brawlers", 3), 
  ("Fitz", 22, "Bobs Brawlers", 3), 
  ("Garry", 22, "Bobs Brawlers", 3), 
  ("Herbert", 22, "Bobs Brawlers", 3), 
  ("Imogen", 22, "Bobs Brawlers", 3), 
  ("Jack", 22, "Bobs Brawlers", 3);
